### PR TITLE
www: add skeleton ToS/Terms page

### PR DESCRIPTION
**Pull request by jonathaningram**

### CODE REVIEW

**Comment by jonathaningram** [comment]
@m-richo you can push the content changes to this PR.

As discussed, you'll need to put the content in as HTML/JSX into `TermsPage.tsx` - we'll aim for Markdown files long term.

Happy to finish this off myself if necessary so let me know.

**Comment by jonathaningram** [comment]
@m-richo do you still want this?

**Comment by gordcorp** [comment]
@jonathaningram mind taking a look at this before I merge? prettier was complaining, so I figured a `yarn format` was a good idea.

**Comment by jonathaningram** [comment]
@gordcorp lgtm

**Pull request merged**
